Glimpse: add usp support, update params and fpd setup
glimpse-protocol/prebid.github.io pull request #5
Opened 2022-03-18 17:10 UTC by eddieyu1998

# Description

- Add usp support
- Remove demand and keywords bidder params
- Update example on setting up adapter with first party data
- 
## 🏷 Type of documentation

- [ ] new bid adapter
- [x] update bid adapter
- [x] new feature
- [ ] text edit only (wording, typos)
- [ ] bugfix (code examples)
- [x] new examples

## 📋 Checklist

- [ ] Related pull requests in prebid.js or server are linked

2022-03-22 11:38 UTC, tim-hm requested changes
a few tweaks please 🙏

2022-03-22 11:38 UTC, tim-hm commented on dev-docs/bidders/glimpse.md
> +          keywords: "business, finance, crypto", // site specific keywords, separated by comma
these should be in an array

2022-03-25 22:29 UTC, eddieyu1998 commented on dev-docs/bidders/glimpse.md
>  deals_supported: true
https://docs.prebid.org/adops/deals.html#enable-deals-in-prebid

it feels to me it's likely what we are doing right now?

2022-03-25 22:30 UTC, eddieyu1998 commented on dev-docs/bidders/glimpse.md
> +| `placementId` | Required | string | A unique identifier associated with a publisher and ad unit, provided by the Glimpse Publisher Portal when registering a unit | 'glimpse-placement-id' |
we can, I'll update the adapter and test accordingly later

2022-03-29 20:28 UTC, tim-hm approved these changes
I made a few tweaks. Please give it a sanity check and then go ahead and merge 🙏

2022-03-30 10:19 UTC, merged